server:
  port: 8080

spring:
  application:
    name: vidasalud-ms-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/49cd374a-62d5-4d3d-851e-69058d58e3b5/discovery/v2.0/keys

services:
  appointments-url: ${APPOINTMENTS_URL:http://localhost:8081}
  catalog-url: ${CATALOG_URL:http://localhost:8082}

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:4200,http://localhost:4201}

logging:
  level:
    org.springframework.security: INFO
